global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']  # Prometheus server
  - job_name: 'minio'
    static_configs:
      - targets: ['my-minio:9000']  # Minio server
