name: fraganal
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - geopandas
  - seaborn
  - pip:
    - ipykernel
    - openpyxl
    - pyarrow
    - pycountry
    - plotly
